name: Coverage

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  compile-web:
    name: Compile Board Web Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.16.5

      - name: Install dependencies
        run: |
          cargo binstall --no-confirm trunk

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install npm dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: trunk build --release
        working-directory: crates/web

      - name: Cache cargo registry and trunk assets
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            crates/web/dist
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: compile-web
    steps:
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Cache cargo registry and trunk assets
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            crates/web/dist
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: Generate code coverage
        run: cargo tarpaulin --all-features --verbose --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          file: cobertura.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
